# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3085013317960def65d7f15e0f313c57786df9fe410e918b6d4b92a73e5cbc7f6697e4ab5ef9bc20dced3629854ed9aa44d665961a5e7422f5ed24cb052e849

test:
  secret_key_base: c60c1a824eee1b366d400cf04c873a48165fb8b8f5ac42ba98b77dd01255612a82778099fe2ba4925831e81f604e6c2de005beca89bde1ca21f0d84aed7115d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
